

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josehumbertoabrilgarcia
 */
public class NewJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    private Dimension size;
    private String codigo = "";
    private int width, height;
    
    public NewJFrame() {
       
        initComponents();
        
        size = Toolkit. getDefaultToolkit(). getScreenSize();
        
        width=Toolkit. getDefaultToolkit(). getScreenSize().width;
        height=Toolkit. getDefaultToolkit(). getScreenSize().height;
        
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);
                
        this.setLayout(null);
        
        //jLabel1.setLocation(this.getWidth()/2 - jLabel1.getWidth()/2, 0);
        
        //jLabel2.setLocation(this.getWidth()/2 - jLabel2.getWidth()/2, jLabel1.getLocation().y+jLabel1.getHeight());
        
        // preferredSize= 305, 165  
        
        jLabel3.setText("<html><img src='file:C:\\Users\\Ricardo\\Desktop\\VerificadorPreciosJava-main\\VerificadorDePrecios\\src\\main\\java\\Cosco2.png' width='305' height='165'>");
        
        jLabel3.setLocation(this.getWidth()/2-jLabel3.getWidth()/2, 10);

        // preferredSize= 120, 120  
        
        jLabel4.setText("<html><img src='file:C:\\Users\\Ricardo\\Desktop\\VerificadorPreciosJava-main\\VerificadorDePrecios\\src\\main\\java\\Codigo-de-barras.gif' width='120' height='120'>");

        jLabel4.setLocation(this.getWidth()/2-jLabel4.getWidth()/2, this.getHeight()/2 + jLabel3.getHeight() + 10);
     
        //jLabel4.setLocation(this.getWidth()/2 - jLabel4.getWidth()/2 , jLabel3.getLocation().y + jLabel3.getHeight() + 10);
        
        jLabel5.setSize(width-200,150);
        jLabel5.setText("Pase el producto por el escaner por favor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(Toolkit. getDefaultToolkit(). getScreenSize().width, Toolkit. getDefaultToolkit(). getScreenSize().height);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(305, 165));

        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 120));

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 36)); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(254, 254, 254)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
      
        //JOptionPane.showMessageDialog(null, evt.getKeyCode());
        if (evt.getKeyCode()!= 10) {
            codigo += evt.getKeyChar();
        }
        else{
            //JOptionPane.showMessageDialog(null, "El codigo presionado es " + codigo);
            try{
                Connection con = null;
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/productos_usuarios","root","");
                Statement stmt = con.createStatement();
                ResultSet rs=stmt.executeQuery("SELECT * FROM productos WHERE id = "+codigo);
                
                //Aquí los índices empiezan en 1
                
                if(rs.next()){
                    //rs.next();
                    //JOptionPane.showMessageDialog(null, rs.getString(1));
                    
                    jLabel5.setSize(width-200,150);         //width = ancho     height = alto
                    
                    //jLabel4.setSize(300,300);
                    //jLabel4.setText("<html><img src='"+ rs.getString(4) +"' width='300' height='300'>");
                    
                    
                    jLabel4.setText("<html><img src='"+ rs.getString(4) +"' width='800' height='800'>");
        
                    jLabel4.setLocation(25,25);
                    
                    
                    //jLabel5.setPreferredSize(new Dimension(width, 24));
                    jLabel5.setText("<html>Nombre: "+rs.getString(1)+"<br>Precio: "+rs.getString(2)+"<br>Cantidad en almacén: "+rs.getString(3));
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Producto no encontrado, llame a personal autorizado");
                }
                
                //JOptionPane.showMessageDialog(null, "SELECT * FROM productos WHERE producto_codigo = "+codigo);
            }catch(ClassNotFoundException e){
              JOptionPane.showMessageDialog(null, e.toString());  
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error"+e.toString());
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e.toString());
            }
            codigo = "";
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
